Repository Onederful-Project/spring-onederful, pull requests merged in 2025-06, with the labels that each got.

#3 [#2] Entity 기본생성 / 파일구조 작업
  onederful.sql
  src/main/java/com/example/onederful/OnederfulApplication.java
  src/main/java/com/example/onederful/config/.gitkeep
  src/main/java/com/example/onederful/domain/comment/controller/.gitkeep
  src/main/java/com/example/onederful/domain/comment/dto/.gitkeep
  src/main/java/com/example/onederful/domain/comment/entity/Comment.java
  src/main/java/com/example/onederful/domain/comment/repository/.gitkeep
  src/main/java/com/example/onederful/domain/comment/service/.gitkeep
  src/main/java/com/example/onederful/domain/log/controller/.gitkeep
  src/main/java/com/example/onederful/domain/log/dto/.gitkeep
  src/main/java/com/example/onederful/domain/log/entity/Log.java
  src/main/java/com/example/onederful/domain/log/enums/Activity.java
  src/main/java/com/example/onederful/domain/log/enums/Method.java
  src/main/java/com/example/onederful/domain/log/repository/.gitkeep
  src/main/java/com/example/onederful/domain/log/service/.gitkeep
  src/main/java/com/example/onederful/domain/task/controller/.gitkeep
  src/main/java/com/example/onederful/domain/task/dto/.gitkeep
  src/main/java/com/example/onederful/domain/task/entity/Task.java
  src/main/java/com/example/onederful/domain/task/enums/Priority.java
  src/main/java/com/example/onederful/domain/task/enums/ProcessStatus.java
  src/main/java/com/example/onederful/domain/task/repository/.gitkeep
  src/main/java/com/example/onederful/domain/task/service/.gitkeep
  src/main/java/com/example/onederful/domain/user/controller/.gitkeep
  src/main/java/com/example/onederful/domain/user/dto/.gitkeep
  src/main/java/com/example/onederful/domain/user/entity/User.java
  src/main/java/com/example/onederful/domain/user/enums/Role.java
  src/main/java/com/example/onederful/domain/user/repository/.gitkeep
  src/main/java/com/example/onederful/domain/user/service/.gitkeep
  src/main/java/com/example/onederful/exception/.gitkeep
  src/main/java/com/example/onederful/filter/.gitkeep
  src/main/java/com/example/onederful/security/.gitkeep
  src/main/resources/application.properties
Labels: 🚀 feature

#13 [#12] Swagger 도입
  build.gradle
  src/main/java/com/example/onederful/config/SwaggerConfig.java
  src/main/java/com/example/onederful/filter/JwtFilter.java
Labels: 🚀 feature

#16 Feature/6 댓글기능 CRUD
  src/main/java/com/example/onederful/domain/comment/controller/CommentController.java
  src/main/java/com/example/onederful/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/example/onederful/domain/comment/dto/CommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/dto/CreateCommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/dto/ResponseDto.java
  src/main/java/com/example/onederful/domain/comment/dto/UpdateCommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/entity/Comment.java
  src/main/java/com/example/onederful/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/onederful/domain/comment/service/CommentService.java
  src/main/java/com/example/onederful/exception/ErrorCode.java
Labels: 🚀 feature

#17 Feature/7
  build.gradle
  src/main/java/com/example/onederful/domain/dashboard/controller/DashboardController.java
  src/main/java/com/example/onederful/domain/dashboard/dto/ApiResponse.java
  src/main/java/com/example/onederful/domain/dashboard/dto/MyTasksTodayResponseDto.java
  src/main/java/com/example/onederful/domain/dashboard/dto/StatisticsResponseDto.java
  src/main/java/com/example/onederful/domain/dashboard/repository/DashboardRepository.java
  src/main/java/com/example/onederful/domain/dashboard/repository/DashboardRepositoryImpl.java
  src/main/java/com/example/onederful/domain/dashboard/service/DashboardService.java
  src/main/java/com/example/onederful/exception/ErrorCode.java
Labels: 🚀 feature

#19 feat : CORS 설정 , 필터 등록
  src/main/java/com/example/onederful/config/WebConfig.java
  src/main/java/com/example/onederful/filter/JwtFilter.java
Labels: 🚀 feature

#29 Feature/21 댓글 TestCode 작성
  src/main/java/com/example/onederful/domain/comment/controller/CommentController.java
  src/test/java/com/example/onederful/domain/comment/service/CommentServiceTest.java
Labels: 🚀 feature

#27 [#5] AOP 활동 로그 기록
  src/main/java/com/example/onederful/domain/log/HttpRequestUtil.java
  src/main/java/com/example/onederful/domain/log/LoggingAspect.java
  src/main/java/com/example/onederful/domain/log/controller/.gitkeep
  src/main/java/com/example/onederful/domain/log/controller/LogController.java
  src/main/java/com/example/onederful/domain/log/dto/.gitkeep
  src/main/java/com/example/onederful/domain/log/dto/LogResponse.java
  src/main/java/com/example/onederful/domain/log/dto/LogsResponse.java
  src/main/java/com/example/onederful/domain/log/enums/Activity.java
  src/main/java/com/example/onederful/domain/log/repository/.gitkeep
  src/main/java/com/example/onederful/domain/log/repository/LogRepository.java
  src/main/java/com/example/onederful/domain/log/repository/LogSpecification.java
  src/main/java/com/example/onederful/domain/log/service/.gitkeep
  src/main/java/com/example/onederful/domain/log/service/LogService.java
  src/main/java/com/example/onederful/exception/ErrorCode.java
Labels: 🚀 feature

#33 refactor : 댓글 응답 형식 수정
  src/main/java/com/example/onederful/domain/comment/controller/CommentController.java
  src/main/java/com/example/onederful/domain/comment/dto/CommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/dto/CreateCommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/dto/ResponseDto.java
  src/main/java/com/example/onederful/domain/comment/dto/UpdateCommentResponseDataDto.java
  src/main/java/com/example/onederful/domain/comment/dto/UserData.java
  src/main/java/com/example/onederful/domain/comment/service/CommentService.java
  src/test/java/com/example/onederful/domain/comment/service/CommentServiceTest.java
Labels: 🛠 refactor

#41 [#39] 테스트 코드 / 요구사항과 다른 코멘트 삭제 부분 버그 수정
  src/main/java/com/example/onederful/domain/comment/controller/CommentController.java
  src/main/java/com/example/onederful/domain/log/controller/LogController.java
  src/main/java/com/example/onederful/domain/log/dto/LogsResponse.java
  src/main/java/com/example/onederful/domain/log/service/LogService.java
  src/test/java/com/example/onederful/domain/task/service/TaskServiceTest.java
Labels: 🐞 bug

#43 [#42] README 운영환경변수 추가 / 오타 수정
  README.md
  src/main/resources/application.yml
Labels: 🚀 feature
